version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
      time: "12:00"
    labels:
      - "Env: Dependencies"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    assignees:
      - "kitsudaiki"