name: build-and-test

on: [push]

permissions:
  contents: read
  pull-requests: read

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy-check:
    name: cargo clippy
    runs-on: ubuntu-24.04
    steps:
      -
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
      -
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        name: Run Clippy
        run: cargo clippy --all-targets --all-features


  rustfmt-check:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48
        with:
          components: rustfmt
      -
        name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@559aa3035a47390ba96088dffa783b5d26da9326


  check-for-executables:
    name: "Detect binary executables"
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        name: Run binary files check script
        run: |
          git ls-tree -r HEAD --name-only | while read filename; do
            # Check if the file is a binary
            if [[ $(file -b --mime-encoding "$filename") == binary ]] && file -b "$filename" | grep -q "executable"; then
              echo "Binary file found: $filename"
              exit 1
            fi
          done
          exit 0


  commit-lint:
    name: "Lint commits"
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        name: lint commits
        uses: wagoid/commitlint-github-action@7f0a61df502599e1f1f50880aaa7ec1e2c0592f2


  detect-sectets:
    name: "Detect secrets"
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      -
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-venv python3-pip
      -
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        name: Run check
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install detect-secrets
          git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline


  cargo_tests:
    name: "Cargo Test"
    needs: [ clippy-check, rustfmt-check, check-for-executables, commit-lint, detect-sectets ]
    runs-on: ubuntu-24.04
    steps:
      -
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
      -
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        name: Run Cargo-Test
        run: cargo test -- --test-threads=1


  pip_test:
    name: "Pip Test"
    needs: [ cargo_tests ]
    runs-on: ubuntu-24.04
    steps:
      -
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
      -
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      -
        name: Prepare
        run: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip3 install maturin
      -
        name: Build
        run: |
          source .venv/bin/activate
          maturin develop
      -
        name: Run test
        run: |
          source .venv/bin/activate
          python3 test.py


